=== Fuco1/dfraweditor/trunk/dfraweditor/xml/raws.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="raws">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="c" type="t_container" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="t" type="t_token" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="id" type="t_id" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="t_container">
        <xs:sequence>
            <xs:element name="d" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="a" type="t_argument" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="c" type="t_container_inside" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="t" type="t_token_inside" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="t_container_inside">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="required" type="xs:string" default="true"/>
    </xs:complexType>

    <xs:complexType name="t_token">
        <xs:sequence>
            <xs:element name="d" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="a" type="t_argument" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="t_token_inside">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="required" type="xs:string" default="true"/>
    </xs:complexType>

    <xs:complexType name="t_argument">
        <xs:sequence>
            <xs:element name="d" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="e" type="t_enum_item" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="label" type="xs:string"/>
        <xs:attribute name="ref" type="xs:string"/>
        <xs:attribute name="required" type="xs:string" default="true"/>
        <xs:attribute name="min" type="xs:string"/>
        <xs:attribute name="max" type="xs:string"/>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="string"/>
                    <xs:enumeration value="int"/>
                    <xs:enumeration value="range"/>
                    <xs:enumeration value="enum"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="t_enum_item">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="t_id">
        <xs:sequence>
            <xs:element name="d" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="from" type="xs:string"/>
        <xs:attribute name="to" type="xs:string"/>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== Fuco1/dfraweditor/dfraweditor/raws2.xml
<?xml version="1.0" encoding="UTF-8"?>
<raws xsi:noNamespaceSchemaLocation="raws.xsd"
    xmlns=""
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- CREATURES  -->
    <c name="OBJECT:CREATURE">
        <d>A top level container for all creatures</d>
        <c name="CREATURE"/>
    </c>

    <c name="CREATURE">
        <a type="string"/>
        <t name="USE_MATERIAL_TEMPLATE"/>
        <t name="NAME"/>
    </c>

    <t name="USE_MATERIAL_TEMPLATE">
<!--        local name-->
        <a type="string"/>
        <!-- We look into the string->id map for the key "MATERIAL_TEMPLATE_ID" -->
        <!-- If found, we can easily get the list of all available items -->
        <a type="string" ref="MATERIAL_TEMPLATE_ID"/> 
    </t>

    <!-- MATERIAL TEMPLATES -->
    <c name="OBJECT:MATERIAL_TEMPLATE">
        <c name="MATERIAL_TEMPLATE"/>
    </c>

    <c name="MATERIAL_TEMPLATE">
        <!-- If we found an ID that is not yet defined, we create a new ID object -->
        <!-- Then we add whatever content of the argument to the list of available items
        for the given ID -->
        <a type="string" id="MATERIAL_TEMPLATE_ID"/>
        <t name="STATE_NAME"/>
    </c>

    <t name="STATE_NAME">
        <a type="string"/>
        <a type="string"/>
    </t>

    <!-- REACTIONS -->
    <!-- [REACTION:TRAIN_ARMORSMITHING]
             [NAME:practice armorsmithing]
             [BUILDING:TRAINING_WORKSHOP:CUSTOM_A]
             [REAGENT:A:1:ARMOR:NONE:INORGANIC:NONE][PRESERVE_REAGENT]
             [REAGENT:B:150:BAR:NONE:METAL:NONE]
             [REAGENT:C:1:TOY:ITEM_TABLET:NONE:NONE]
             [PRODUCT:80:1:TOY:ITEM_TABLET:GET_MATERIAL_FROM_REAGENT:C:NONE]
             [PRODUCT:90:1:BAR:NONE:GET_MATERIAL_FROM_REAGENT:B:NONE]
             [PRODUCT_DIMENSION:150]
             [SKILL:FORGE_ARMOR] -->
    <c name="REACTION">
        <a type="string" id="REACTION_ID"/>
        <t name="REAGENT"/>
        <t name="PRODUCT"/>
    </c>

    <t name="REAGENT">
        <a type="string"/>
        <a type="int"/>
        <a type="string" ref="ITEM_ID"/>
        <a type="string" ref="ITEM_SUB_ID"/>
        <a type="string" ref="MAT_ID"/>
        <a type="string" ref="MAT_SUB_ID"/>
    </t>

</raws>


<!--    [MATERIAL_TEMPLATE:WOOD_TEMPLATE]
	[STATE_COLOR:ALL_SOLID:BROWN]
	[STATE_NAME:ALL_SOLID:wood]-->

=== Fuco1/dfraweditor/trunk/raws.xml
<?xml version="1.0" encoding="UTF-8"?>
<raws xsi:noNamespaceSchemaLocation="raws.xsd"
    xmlns=""
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
<!--
elements:
c = container, can contain other containers and tokens
t = token, a single directive, contains at least one attribute
a = attribute
e = element of enum
d = description of the container/token/flag/attribute

attributes:
name = the "RAW" name of the RAW
type = type of the attribute (string, int, range, enum)
id   = if true, the attribute is logic id of the object
required = the attribute is required
-->

    <c name="OBJECT:ITEM">
        <d>A top level container for all items</d>
        <c name="ITEM_ARMOR"/>
    </c>

    <c name="ITEM_ARMOR">
        <a type="string" id="ITEM_ARMOR_ID"/>
        
        <t name="ARMORLEVEL"/>
        <t name="COVERAGE"/>
        <t name="LAYER"/>
        <t name="LAYER_SIZE"/>
        <t name="LAYER_PERMIT"/>
        <t name="LBSTEP"/>
        <t name="MATERIAL_SIZE"/>
        <t name="NAME"/>
        <t name="PREPLURAL"/>
        <t name="UBSTEP"/>
        <t name="UPSTEP"/>

        <t name="BARRED"/>
        <t name="HARD"/>
        <t name="LEATHER"/>
        <t name="METAL"/>
        <t name="SCALED"/>
        <t name="SHAPED"/>
        <t name="SOFT"/>
        <t name="STRUCTURAL_ELASTICITY_WOVEN_THREAD"/>
        <t name="STRUCTURAL_ELASTICITY_CHAIN_METAL"/>
    </c>

    <t name="ARMORLEVEL">
        <a type="range" min="0" max="3">
            <d>A range of 0 to 3, specify the strength of the armor</d>
        </a>
    </t>

    <t name="COVERAGE">
        <a type="int"/>
    </t>

    <t name="LAYER">
        <d>This is layer definition token. It defines where the armor is placed</d>
        <a type="enum">
            <d>Possible values for LAYER: armor, over, under</d>
            <e name="ARMOR"/>
            <e name="OVER"/>
            <e name="UNDER"/>
            <e name="COVER"/>
        </a>
    </t>

    <t name="LAYER_SIZE">
        <a type="int"/>
    </t>

    <t name="LAYER_PERMIT">
        <a type="int"/>
    </t>

    <t name="LBSTEP">
        <a type="int"/>
    </t>

    <t name="MATERIAL_SIZE">
        <a type="int"/>
    </t>

    <t name="NAME">
        <a type="string"/>
        <a type="string"/>
    </t>

    <t name="PREPLURAL">
        <a type="string"/>
    </t>

    <t name="UBSTEP">
        <a type="int"/>
    </t>

    <t name="UPSTEP">
        <a type="int"/>
    </t>

    <t name="METAL">
        <d>If present, item can be made out of metal.</d>
    </t>
</raws>
