=== Fuco1/dfraweditor/trunk/keywordtypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="keywordtypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="id" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="color" type="t_color" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="fcolor" type="t_color" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="bold" type="t_flag" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="italic" type="t_flag" minOccurs="0" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="t_color">
        <xs:restriction base="xs:string">
            <xs:pattern value="#([0-9a-fA-F]{2}){3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="t_flag">
        <xs:restriction base="xs:string">
            <xs:length value="0"/>
        </xs:restriction>
    </xs:simpleType>    
</xs:schema>

=== Fuco1/dfraweditor/trunk/keywordtypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<keywordtypes
    xsi:noNamespaceSchemaLocation="keywordtypes.xsd"
    xmlns=""
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <type>
        <id>OBJECT</id>
        <color>#000000</color>
        <bold/>
    </type>

    <type>
        <id>CONTAINER</id>
        <color>#0000e9</color>
    </type>

    <type>
        <id>TOKEN</id>
        <color>#00a000</color>
    </type>

    <type>
        <id>FLAG</id>
        <color>#00a000</color>
        <italic/>
    </type>

    <type>
        <id>ARGUMENT</id>
        <color>#00ff00</color>
    </type>

    <type>
        <id>INT</id>
        <color>#a048a0</color>
    </type>

    <type>
        <id>STRING</id>
        <color>#ce7b00</color>
    </type>
</keywordtypes>
