=== Fuco1/dfraweditor/trunk/dfraweditor/keywords.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="keywords">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="keyword" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="indent" type="t_flag" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="container" type="t_flag" minOccurs="0" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="t_flag">
        <xs:restriction base="xs:string">
            <xs:length value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== Fuco1/dfraweditor/trunk/keywords.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

OBJECT: top level objects defining what objects are in the raw file
ENTITY: an entity in the raw file, it may be item, creature, tissue template...
DIRECTIVE: flag or token inside the entity

-->
<keywords
    xsi:noNamespaceSchemaLocation="keywords.xsd"
    xmlns=""
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <keyword>
        <name>OBJECT</name>
        <type>OBJECT</type>
        <container/>
    </keyword>

    <keyword>
        <name>ITEM_ARMOR</name>
        <type>CONTAINER</type>
        <indent/>
        <container/>
    </keyword>

    <keyword>
        <name>ITEM_HELM</name>
        <type>CONTAINER</type>
        <indent/>
        <container/>
    </keyword>

    <keyword>
        <name>ARMORLEVEL</name>
        <type>TOKEN</type>
    </keyword>

    <keyword>
        <name>NAME</name>
        <type>TOKEN</type>
    </keyword>
    
    <keyword>
        <name>UBSTEP</name>
        <type>TOKEN</type>
    </keyword>
    
    <keyword>
        <name>LBSTEP</name>
        <type>TOKEN</type>
    </keyword>
    
    <keyword>
        <name>LAYER</name>
        <type>TOKEN</type>
    </keyword>
    
    <keyword>
        <name>COVERAGE</name>
        <type>TOKEN</type>
    </keyword>
    
    <keyword>
        <name>LAYER_SIZE</name>
        <type>TOKEN</type>
    </keyword>
    
    <keyword>
        <name>LAYER_PERMIT</name>
        <type>TOKEN</type>
    </keyword>

    <keyword>
        <name>MATERIAL_SIZE</name>
        <type>TOKEN</type>
    </keyword>

    <keyword>
        <name>SHAPED</name>
        <type>FLAG</type>
    </keyword>

    <keyword>
        <name>HARD</name>
        <type>FLAG</type>
    </keyword>

    <keyword>
        <name>METAL</name>
        <type>FLAG</type>
    </keyword>
</keywords>
